# Generated by Django 4.2.7 on 2025-09-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_simplelogin_fields'),
    ]

    operations = [
        # Add new fields to DataElement model for comprehensive ESG framework
        migrations.AddField(
            model_name='dataelement',
            name='master_id',
            field=models.CharField(max_length=20, unique=True, null=True, blank=True,
                                 help_text='Unique master ID from Excel (e.g., HOSP-E-001)'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='esg_category',
            field=models.CharField(max_length=1, choices=[('E', 'Environmental'), ('S', 'Social'), ('G', 'Governance')],
                                 null=True, blank=True, help_text='ESG category from Excel'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='requirement_type',
            field=models.CharField(max_length=20, choices=[('must-have', 'Must Have'), ('conditional', 'Conditional')],
                                 null=True, blank=True, help_text='Whether element is required or conditional'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='frameworks',
            field=models.CharField(max_length=100, null=True, blank=True,
                                 help_text='Applicable frameworks (E/D/G) from Excel'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='cadence',
            field=models.CharField(max_length=20, null=True, blank=True,
                                 help_text='Collection frequency (monthly, annual, etc.)'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='is_derived',
            field=models.BooleanField(default=False,
                                    help_text='Whether this element is calculated (D) or collected (C)'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='ghg_scope',
            field=models.CharField(max_length=10, null=True, blank=True,
                                 help_text='GHG scope (1, 2, 3) if applicable'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='condition_logic',
            field=models.TextField(null=True, blank=True,
                                 help_text='Business logic condition for conditional elements'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='wizard_question',
            field=models.TextField(null=True, blank=True,
                                 help_text='Question text for profiling wizard'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='detailed_prompt',
            field=models.TextField(null=True, blank=True,
                                 help_text='Detailed instructions for data collection'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='legacy_element_id',
            field=models.CharField(max_length=50, null=True, blank=True,
                                 help_text='Store old element_id for backward compatibility'),
        ),
    ]
