# Generated by Django 4.2.7 on 2025-09-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_comprehensive_esg_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active_frameworks',
            field=models.JSONField(default=list, help_text="List of active framework codes ['E', 'D', 'G']"),
        ),
        migrations.AddField(
            model_name='company',
            name='has_green_key',
            field=models.BooleanField(default=False, help_text='Company has Green Key certification'),
        ),
    ]
