# Generated by Django 4.2.7 on 2025-10-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_framework_tracking_to_company'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='companychecklist',
            index=models.Index(fields=['company', 'cadence'], name='idx_company_cadence'),
        ),
        migrations.AddIndex(
            model_name='companychecklist',
            index=models.Index(fields=['company', 'element'], name='idx_company_element'),
        ),
        migrations.AddIndex(
            model_name='companychecklist',
            index=models.Index(fields=['company'], name='idx_company_checklist'),
        ),
        migrations.AddIndex(
            model_name='companydatasubmission',
            index=models.Index(fields=['company', 'reporting_year', 'reporting_period'], name='idx_company_year_period'),
        ),
        migrations.AddIndex(
            model_name='companydatasubmission',
            index=models.Index(fields=['company', 'element'], name='idx_submission_company_element'),
        ),
        migrations.AddIndex(
            model_name='companydatasubmission',
            index=models.Index(fields=['company', 'assigned_to'], name='idx_company_assigned_to'),
        ),
        migrations.AddIndex(
            model_name='companydatasubmission',
            index=models.Index(fields=['company'], name='idx_submission_company'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['company', 'type'], name='idx_meter_company_type'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['company', 'status'], name='idx_meter_company_status'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['company'], name='idx_meter_company'),
        ),
    ]
