# Generated by Django 4.2.7 on 2025-10-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companydatasubmission',
            name='idx_company_assigned_to',
        ),
        migrations.RemoveIndex(
            model_name='meter',
            name='idx_meter_company_type',
        ),
        migrations.RemoveIndex(
            model_name='meter',
            name='idx_meter_company_status',
        ),
        migrations.RemoveIndex(
            model_name='meter',
            name='idx_meter_company',
        ),
        migrations.RenameIndex(
            model_name='companychecklist',
            new_name='idx_checklist_company_element',
            old_name='idx_company_element',
        ),
        migrations.RenameIndex(
            model_name='companychecklist',
            new_name='idx_checklist_company',
            old_name='idx_company_checklist',
        ),
    ]
