# Generated by Django 4.2.7 on 2025-11-21 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_add_tasks_api_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique feature flag key', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable feature name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this feature controls')),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('email', 'Email Services'), ('data_collection', 'Data Collection'), ('user_management', 'User Management'), ('api', 'API Access'), ('ui', 'User Interface'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('performance', 'Performance')], default='ui', max_length=50)),
                ('flag_type', models.CharField(choices=[('boolean', 'Boolean Toggle'), ('string', 'String Value'), ('integer', 'Integer Value'), ('json', 'JSON Configuration')], default='boolean', max_length=20)),
                ('boolean_value', models.BooleanField(default=False)),
                ('string_value', models.CharField(blank=True, max_length=500)),
                ('integer_value', models.IntegerField(default=0)),
                ('json_value', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this flag is enabled in the system')),
                ('requires_restart', models.BooleanField(default=False, help_text='Whether changes require server restart')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['category', 'name'],
            },
        ),
    ]
